import math
import time
import numpy as np
import logging

logger = logging.getLogger(__name__)


class EKFFusion:
    """
    Extended Kalman Filter for fusing GPS (UTM) and IMU (Quaternions/Accel).
    Includes an active Accelerometer Bias state to eliminate dead-reckoning drift.
    """

    def __init__(self, debug=False):
        self.debug = debug
        # State Vector [x, y, yaw, velocity, accel_bias]
        self.x = np.zeros((5, 1))

        # Covariance Matrix (Our uncertainty about the state)
        self.P = np.eye(5) * 1.0

        # Process Noise (Q) - How much do we distrust our predictions?
        self.Q = np.diag([
            0.05,  # variance in x
            0.05,  # variance in y
            0.05,  # variance in yaw
            0.05,  # variance in velocity
            0.0001  # variance in accel_bias (Very small! Bias changes very slowly)
        ])

        # Measurement Noise (R) - How much do we distrust the GPS?
        self.R = np.diag([
            10.0,  # GPS X variance in meters
            10.0  # GPS Y variance in meters
        ])

        # Measurement Matrix (H) - Maps state to measurement [x, y]
        self.H = np.array([
            [1.0, 0.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0, 0.0]
        ])

        # Low-Pass Filter (EMA) Setup
        self.alpha = 0.10  # Lower = smoother data but more lag. Higher = more jagged data but faster.
        self.smoothed_x = None
        self.smoothed_y = None

        self.last_time = time.time()
        self.last_gps = (0.0, 0.0)
        self.initialized = False

    def _quat_to_yaw(self, qi, qj, qk, qr):
        siny_cosp = 2 * (qr * qk + qi * qj)
        cosy_cosp = 1 - 2 * (qj * qj + qk * qk)
        return math.atan2(siny_cosp, cosy_cosp)

    def run(self, gps, accel, gyro, quat):
        gps_x, gps_y = gps
        ax, ay, az = accel
        gx, gy, gz = gyro
        qi, qj, qk, qr = quat

        # Graceful fallback if sensors are still booting up
        if any(v is None for v in [gps_x, gps_y, ax, qi]):
            return 0.0, 0.0, 0.0

        current_time = time.time()
        dt = current_time - self.last_time
        self.last_time = current_time

        yaw = self._quat_to_yaw(qi, qj, qk, qr)

        # ---------------------------------------------------------
        # 1. INITIALIZATION
        # ---------------------------------------------------------
        if not self.initialized:
            if gps_x != 0.0 and gps_y != 0.0:
                self.x[0, 0] = gps_x
                self.x[1, 0] = gps_y
                self.x[2, 0] = yaw
                self.x[3, 0] = 0.0
                self.x[4, 0] = 0.0  # Assume 0 bias to start
                self.last_gps = (gps_x, gps_y)
                self.initialized = True
            return gps_x, gps_y, yaw

        # ---------------------------------------------------------
        # 2. PREDICTION STEP
        # ---------------------------------------------------------
        if abs(ay) < 0.2: 
            ay = 0.0

        # Calculate true acceleration by subtracting our estimated bias
        true_ax = ay - self.x[4, 0]

        # 2. Velocity Decay (Artificial Friction)
        # Multiplier slowly bleeds off fake velocity generated by GPS noise
        friction_factor = 0.95 
        v_pred = (self.x[3, 0] * friction_factor) + (true_ax * dt)

        # Non-linear state transition
        self.x[0, 0] = self.x[0, 0] + v_pred * math.cos(self.x[2, 0]) * dt
        self.x[1, 0] = self.x[1, 0] + v_pred * math.sin(self.x[2, 0]) * dt
        self.x[2, 0] = yaw
        self.x[3, 0] = v_pred
        # self.x[4, 0] remains unchanged during prediction (constant bias model)

        # Calculate the Jacobian (F) matrix
        F = np.eye(5)
        F[0, 2] = -v_pred * math.sin(self.x[2, 0]) * dt
        F[0, 3] = math.cos(self.x[2, 0]) * dt
        F[1, 2] = v_pred * math.cos(self.x[2, 0]) * dt
        F[1, 3] = math.sin(self.x[2, 0]) * dt
        F[3, 4] = -dt  # This links the bias variable to velocity error

        # Update Covariance
        self.P = F @ self.P @ F.T + self.Q

        # ---------------------------------------------------------
        # 3. UPDATE STEP (Pull position back to reality using GPS)
        # ---------------------------------------------------------
        if gps_x != 0.0 and gps_y != 0.0 and (gps_x, gps_y) != self.last_gps:
            z = np.array([[gps_x], [gps_y]])

            # Calculate Kalman Gain
            S = self.H @ self.P @ self.H.T + self.R
            K = self.P @ self.H.T @ np.linalg.inv(S)

            # Residual (Difference between GPS and our Prediction)
            y = z - (self.H @ self.x)

            # Correct the state and covariance (this naturally adjusts self.x[4, 0]!)
            self.x = self.x + (K @ y)
            self.P = (np.eye(5) - (K @ self.H)) @ self.P

            self.last_gps = (gps_x, gps_y)

        # ---------------------------------------------------------
        # 4. OUTPUT
        # ---------------------------------------------------------
        raw_x = float(self.x[0, 0])
        raw_y = float(self.x[1, 0])
        yaw = float(self.x[2, 0])

        # Initialize the EMA filter on the very first loop
        if self.smoothed_x is None or self.smoothed_y is None:
            self.smoothed_x = raw_x
            self.smoothed_y = raw_y
        else:
            # Apply the Exponential Moving Average formula to X and Y
            self.smoothed_x = (self.alpha * raw_x) + ((1.0 - self.alpha) * self.smoothed_x)
            self.smoothed_y = (self.alpha * raw_y) + ((1.0 - self.alpha) * self.smoothed_y)

        if self.debug:
            logger.info(f"EKF FUSED: X={self.smoothed_x:.4f}, Y={self.smoothed_y:.4f}, Yaw={yaw:.4f}")

        return self.smoothed_x, self.smoothed_y, yaw

    def shutdown(self):
        pass