---

- name: install keyboard-configuration
  become: yes
  apt:
    name:
      - keyboard-configuration
      - console-setup
    state: present
  when: ansible_os_family == 'Debian'

- name: write keyboard configration
  become: yes
  template:
    src: keyboards.j2
    dest: /etc/default/keyboard
    force: yes
    owner: root
    group: root
    mode: 'u=rw,go=r'
  notify:
    - dpkg-reconfigure keyboard-configuration
