name: Python package and test

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:

jobs:
  checkout-test:
    name: Checkout and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.13']
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Create python ${{ matrix.python-version }} conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: donkey
          auto-activate: false
          channels: defaults, conda-forge, pytorch
          channel-priority: true
      - name: Conda info and list
        run: |
          conda info
          conda list
      - name: Install donkey
        run: pip install -e .[pc,dev]
      - name: Run tests
        run: pytest
